name: Destroy Terraform Infra

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy (dev/test/prod)'
        required: true
        default: 'dev'

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./templates

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Select Workspace
        run: terraform workspace select -or-create ${{ github.event.inputs.environment }}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
        
      - name: Select Workspace
        run: terraform workspace select -or-create ${{ github.event.inputs.environment }}

      - name: Destroy Infrastructure
        run: terraform destroy -auto-approve -input=false

